format_version: 10
pipelines:
  master-ami:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/raju-b72/master-ami.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:II3GazUX2Axs2MyxWBR93w==:O8SLtfHszWHwMSov2wQnaubhnJUhUKuQuynl/I7u7S8=
    stages:
      - CREATE:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: { command: terraform, arguments: [ "init"], run_if: passed }
                - exec: { command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed }
      - DELETE:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: { command: terraform, arguments: [ "init" ], run_if: passed }
                - exec: { command: terraform, arguments: [ "state", "rm", "aws_ami_from_instance.ami" ], run_if: passed }
                - exec: { command: terraform, arguments: [ "destroy", "-auto-approve" ], run_if: passed }